/gazebo_ros_control:   
  pid_gains:
    front_left_wheel_link_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    front_right_wheel_link_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    rear_left_wheel_link_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    rear_right_wheel_link_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
      
